### ISSUE TITLE
Duplicated Synapse URIs are downloaded multuple times

### ISSUE THREAD

**Issue by adamjtaylor** [Sage-Bionetworks-Workflows/nf-synapse-stage#10]
As a workflow user I wish to stage files from Synapse using sample sheets where the same synapse URI may appear multiple times. 
As each `synapse_get` process is run independently, these are downloaded every time. This could result in increased egress costs.

An improvement would be to run 1 `synapse_get` for each unique Synapse URI detected.

**Comment by BrunoGrandePhD** [comment]
@adamjtaylor: Thanks for reporting this issue! I hadn't thought of this situation. I opened a tiny PR that should do the trick here: #11. When you have a chance, could you try it out and confirm that it behaves as you expect it to? When launching `synstage` in Tower, you should be able to specify the revision as `bgrande/issue-10/avoid-duplicate-downloads`.
