### ISSUE TITLE
Add step to double check that staged files actually exist after all other jobs completed

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks-Workflows/nf-synapse-stage#13]
Recently, when running this workflow to stage very large (150+ GB WGS files), the workflow reports that all synapse_get jobs succeed when in actuality a subset of the files are not present in the target S3 bucket (more discussion here; https://sagebionetworks.slack.com/archives/C048RL0RY74/p1695317841147829). It would be helpful to have a wrap-up step to confirm that all of the paths in update_input actually exist, and fail the workflow if they are not all present. Previously, I trusted the Tower job status output that the files were successfully staged, but I'm not sure that in the current configuration we can really trust that.

**Comment by BWMac** [comment]
Hi @allaway! We are deprecating this repository and instead maintaining its functionality in [`nf-synapse`](https://github.com/Sage-Bionetworks-Workflows/nf-synapse). I have created this Jira [ticket](https://sagebionetworks.jira.com/browse/IBCDPE-911) to track this issue, but I will close it here.
