### ISSUE TITLE
The sed expression with`\b` doesn't seem to work on mac unix.

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks-Workflows/nf-synapse-stage#2]
If you have the synapseids on the first column, the `sed` command doesn't seem to replace anything in `input.staging.txt`.

input.txt

```
syn://syn25890020
```

Command:
```
nextflow run main.nf --input test/input.txt --outdir out --synapse_config ~/.synapseConfig
```

but with Docker it works.

```
nextflow run main.nf --input test/input.txt --outdir out --synapse_config ~/.synapseConfig -with-docker
```

**Comment by BrunoGrandePhD** [comment]
I won't address this because the workflow shouldn't be used without containers.
