### ISSUE TITLE
Add synapse ids or synapse URIs to output file

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks-Workflows/nf-synapse-stage#5]
It might be helpful to include the synapse URI or ID in the output file (maybe it already does this - I'm just basing this comment off of the README in #4 ) as  a "used" column. I think this will help simplify "manual" annotation joins now, but may also make annotations and provenance easier down the road?

**Comment by BrunoGrandePhD** [comment]
Just to make sure I understand, do you want to include the Synapse ID in the file path of the staged S3 object? If so, that's already being done (see example below). Or are you referring to the workflow output files that will be indexed by nf-synindex (since you're alluding to provenance)?

```
$ aws s3 ls s3://jhu-biobank-nf-project-tower-bucket/synapse/ --recursive

s3://jhu-biobank-nf-project-tower-bucket/synapse/syn23564506/GTGCTTAC-AGGAGGAA_S79_L001_R1_001.fastq.gz
s3://jhu-biobank-nf-project-tower-bucket/synapse/syn23564511/GTGCTTAC-AGGAGGAA_S79_L001_R2_001.fastq.gz
s3://jhu-biobank-nf-project-tower-bucket/synapse/syn23564576/ATCTCGCT-GCCTTGTT_S29_L001_R1_001.fastq.gz
s3://jhu-biobank-nf-project-tower-bucket/synapse/syn23564577/ATCTCGCT-GCCTTGTT_S29_L001_R2_001.fastq.gz
```

**Comment by allaway** [comment]
Ah sorry I wasn't clearer. I was thinking it might be useful to include in the staging output file for the purposes of joining with annotations from synapse, or for preparing provenance to go back to synapse: 

```
sample,fastq_1,fastq_2,strandedness, used
foobar,s3://example-bucket/synapse/syn28521174/foobar.R1.fastq.gz,s3://example-bucket/synapse/syn28521175/foobar.R2.fastq.gz,unstranded, synapse_id
```

But now that I look at it more closely, there's not necessarily a 1-row, 1-id relationship, so a `used` column might not make a lot of sense, since in this case it'd actually look like: 

```
sample,fastq_1,fastq_2,strandedness, used
foobar,s3://example-bucket/synapse/syn28521174/foobar.R1.fastq.gz,s3://example-bucket/synapse/syn28521175/foobar.R2.fastq.gz,unstranded, "syn28521174,syn28521175"
```

The IDs are already easy enough to extract from the paths with regex, so maybe this idea is a little half-baked. 😅 I think I'll close this for now!

**Comment by BrunoGrandePhD** [comment]
Oh, I see what you mean by a `used` column! I think tracking the provenance is a good idea. Relying on the file path is hacky. I could look into adding the Synapse URI/ID as a metadata tag on the S3 object, but that's not super discoverable. 

I think I will naturally revisit how we track provenance for staged files once we start designing our workflow provenance MVP. Stay tuned!
