### ISSUE TITLE
Increase memory for `synapse_get` based on attempt

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks-Workflows/nf-synapse-stage#9]
See potential error [here](https://sagebionetworks.slack.com/archives/C8SJHFCKT/p1653315484210499).

**Comment by allaway** [comment]
Thanks for linking this slack thread - I am also running into this issue with synstage (never seen it before - the files are not abnormally large or anything, 2-3 GB RNAseq files).

**Comment by allaway** [comment]
(follow up - the config snippet in the linked thread worked and staging was successful!)

**Comment by BrunoGrandePhD** [comment]
Fixed in 150ecf87a2bbb8650539a0e3e6fcd080e10d6394
